# Generated by Django 5.2.2 on 2025-06-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
